version: "3.8"
services:
  postgres:
    image: postgres
    container_name: TriviaDB
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 3YTRIL1Pnxir
      POSTGRES_DB: Trivia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 